In [1]:
import colorsys

def generate_colors(num_colors):
    # Initialize an empty list to store generated colors
    colors = []

    # Generate equally spaced hues
    hue_step = 360 / num_colors
    for i in range(num_colors):
        # Calculate the current hue
        hue = i * hue_step
        # Convert HSL to RGB
        rgb = colorsys.hls_to_rgb(hue / 360, 0.5, 1)
        # Scale RGB values to 0-255 and round them
        rgb = tuple(round(x * 255) for x in rgb)
        colors.append(rgb)

    return colors

# Generate 117 unique colors
num_colors = 117
unique_colors = generate_colors(num_colors)
print(unique_colors)

[(255, 0, 0), (255, 13, 0), (255, 26, 0), (255, 39, 0), (255, 52, 0), (255, 65, 0), (255, 78, 0), (255, 92, 0), (255, 105, 0), (255, 118, 0), (255, 131, 0), (255, 144, 0), (255, 157, 0), (255, 170, 0), (255, 183, 0), (255, 196, 0), (255, 209, 0), (255, 222, 0), (255, 235, 0), (255, 248, 0), (248, 255, 0), (235, 255, 0), (222, 255, 0), (209, 255, 0), (196, 255, 0), (183, 255, 0), (170, 255, 0), (157, 255, 0), (144, 255, 0), (131, 255, 0), (118, 255, 0), (105, 255, 0), (92, 255, 0), (78, 255, 0), (65, 255, 0), (52, 255, 0), (39, 255, 0), (26, 255, 0), (13, 255, 0), (0, 255, 0), (0, 255, 13), (0, 255, 26), (0, 255, 39), (0, 255, 52), (0, 255, 65), (0, 255, 78), (0, 255, 92), (0, 255, 105), (0, 255, 118), (0, 255, 131), (0, 255, 144), (0, 255, 157), (0, 255, 170), (0, 255, 183), (0, 255, 196), (0, 255, 209), (0, 255, 222), (0, 255, 235), (0, 255, 248), (0, 248, 255), (0, 235, 255), (0, 222, 255), (0, 209, 255), (0, 196, 255), (0, 183, 255), (0, 170, 255), (0, 157, 255), (0, 144, 255), (0, 

In [12]:
import nibabel as nib
import numpy as np

# Load NIfTI files
file_paths = ["C:/Users/schoe/Desktop/inferring_body_weight_from_ct_scans/test/heart.nii.gz", "C:/Users/schoe/Desktop/inferring_body_weight_from_ct_scans/test/kidney_right.nii.gz", "C:/Users/schoe/Desktop/inferring_body_weight_from_ct_scans/test/kidney_left.nii.gz"]
nii_objects = [nib.load(file_path) for file_path in file_paths]

# Ensure compatibility (dimensions, orientations, voxel sizes, etc.)

# Get data from each NIfTI file
data_arrays = [nii.get_fdata() for nii in nii_objects]

In [13]:
# Multiply each data array by its index in the list
# This will create unique values for each data array
multiplied_data_arrays = [data_array * (i + 1) for i, data_array in enumerate(data_arrays)]

In [14]:
# find smalles and largest value in all data arrays
min_value = min([np.min(data) for data in data_arrays])
max_value = max([np.max(data) for data in data_arrays])

all_unique_values = np.unique(np.concatenate(data_arrays))

print(min_value, max_value)
print(all_unique_values)

0.0 1.0
[0. 1.]


In [15]:
# find smalles and largest value in all data arrays
min_value = min([np.min(data) for data in multiplied_data_arrays])
max_value = max([np.max(data) for data in multiplied_data_arrays])

all_unique_values = np.unique(np.concatenate(multiplied_data_arrays))

print(min_value, max_value)
print(all_unique_values)

0.0 3.0
[0. 1. 2. 3.]


In [17]:
# Combine all data arrays into a single array, by overlaying them.
# Take all values from the first array, and replace zeros with values from the second array, and so on.
combined_data_array = np.zeros(data_arrays[0].shape)
for data_array in multiplied_data_arrays:
    combined_data_array = np.where(combined_data_array == 0, data_array, combined_data_array)

In [19]:
# find smalles and largest value in all data arrays
min_value = min([np.min(data) for data in combined_data_array])
max_value = max([np.max(data) for data in combined_data_array])

all_unique_values = np.unique(np.concatenate(combined_data_array))

print(min_value, max_value)
print(all_unique_values)

0.0 3.0
[0. 1. 2. 3.]


In [20]:
combined_data_array.shape

(512, 512, 293)

In [21]:
combined_data_array

array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       ...,

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0.

In [22]:
# Create a new NIfTI image with the merged data
merged_nii = nib.Nifti1Image(combined_data_array, affine=nii_objects[0].affine)

# Save the merged NIfTI file
nib.save(merged_nii, "C:/Users/schoe/Desktop/inferring_body_weight_from_ct_scans/combined_test/combined_scan.nii.gz")